{
  "openapi": "3.0.1",
  "info": {
    "title": "ISC Example Swagger Specs",
    "description": "Example specification of how a API might look using the ISC schemas",
    "version": "1.0",
    "contact": {
      "name": "Animal Data Exchange Working Group",
      "url": "https://www.icar.org/index.php/technical-bodies/working-groups/animal-data-exchange-wg/",
      "email": "icar@icar.org"
    }
  },
  "tags": [{
      "name": "additions",
      "description": "new endpoints not yet approved"
    }
  ],
  "paths": {
    "/locations/{location-scheme}/{location-id}/milking-visits": {
      "get": {
        "operationId": "get-milking-visits",
        "summary": "Get the data for milking visits",
        "description": "# Purpose\nProvides data from visits of animals to a milking parlour.\n \nThis comprises all possible data. Anybody can choose to define API's that return less information in the response.\n",
        "tags": [
          "ADE-1-milk"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          },
          {
            "$ref": "#/components/parameters/start-date-time"
          },
          {
            "$ref": "#/components/parameters/end-date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the milking results for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarMilkingVisitEventCollection"
                },
                "examples": {
                  "base": {
                    "$ref": "#/components/examples/milking-visit"
                  }
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/test-day-results": {
      "get": {
        "operationId": "get-test-day-results",
        "summary": "Get the data for test day results",
        "description": "# Purpose\nProvides data from the test day for animals on a farm\n",
        "tags": [
          "ADE-1-milk"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          },
          {
            "$ref": "#/components/parameters/start-date-time"
          },
          {
            "$ref": "#/components/parameters/end-date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the test day results for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarTestDayResultEventCollection"
                },
                "examples": {
                  "base": {
                    "$ref": "#/components/examples/test-day-result"
                  }
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/lactations": {
      "get": {
        "operationId": "get-lactations",
        "summary": "Get the data for lactations",
        "description": "# Purpose\nProvides data from lactations of animals.",
        "tags": [
          "ADE-1-milk"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the milking results for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarLactationCollection"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/births": {
      "get": {
        "operationId": "get-births",
        "summary": "Get the births for a certain location",
        "description": "# Purpose\nProvides the born animals on a location\n",
        "tags": [
          "ADE-1-registration"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          },
          {
            "$ref": "#/components/parameters/start-date-time"
          },
          {
            "$ref": "#/components/parameters/end-date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the births for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarMovementBirthEventCollection"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/deaths": {
      "get": {
        "operationId": "get-deaths",
        "summary": "Get the deaths for a certain location",
        "description": "# Purpose\nProvides the died animals on a location\n",
        "tags": [
          "ADE-1-registration"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          },
          {
            "$ref": "#/components/parameters/start-date-time"
          },
          {
            "$ref": "#/components/parameters/end-date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the died animals for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarMovementDeathEventCollection"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/arrivals": {
      "get": {
        "operationId": "get-arrivals",
        "summary": "Get the arrivals for a certain location",
        "description": "# Purpose\nProvides the arrived animals on a location\n",
        "tags": [
          "ADE-1-registration"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          },
          {
            "$ref": "#/components/parameters/start-date-time"
          },
          {
            "$ref": "#/components/parameters/end-date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the arrived animals for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarMovementArrivalEventCollection"
                },
                "examples": {
                  "base": {
                    "$ref": "#/components/examples/arrival"
                  }
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/departures": {
      "get": {
        "operationId": "get-departures",
        "summary": "Get the departures for a certain location",
        "description": "# Purpose\nProvides the departed animals from a location\n",
        "tags": [
          "ADE-1-registration"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          },
          {
            "$ref": "#/components/parameters/start-date-time"
          },
          {
            "$ref": "#/components/parameters/end-date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the milking results for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarMovementDepartureEventCollection"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/animals": {
      "get": {
        "operationId": "get-animals",
        "summary": "Get the animals for a certain location",
        "description": "# Purpose\nProvides the animals on a location\n",
        "tags": [
          "ADE-1-registration"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the animals for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarAnimalCoreCollection"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/pregnancy-checks": {
      "get": {
        "operationId": "get-pregnancy-checks",
        "summary": "Get the pregnancy checks for a certain location",
        "description": "# Purpose\nProvides the pregnancy checks on a location\n",
        "tags": [
          "ADE-1-reproduction"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          },
          {
            "$ref": "#/components/parameters/start-date-time"
          },
          {
            "$ref": "#/components/parameters/end-date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the pregnancy diagnosis for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarReproPregnancyCheckEventCollection"
                },
                "examples": {
                  "finland": {
                    "$ref": "#/components/examples/pregnancy-check-finland"
                  }
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/heats": {
      "get": {
        "operationId": "get-Heats",
        "summary": "Get the heats for a certain location",
        "description": "# Purpose\nProvides the Heats on a location\n",
        "tags": [
          "ADE-1-reproduction"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          },
          {
            "$ref": "#/components/parameters/start-date-time"
          },
          {
            "$ref": "#/components/parameters/end-date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the heats for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarReproHeatEventCollection"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/inseminations": {
      "get": {
        "operationId": "get-inseminations",
        "summary": "Get the inseminations for a certain location",
        "description": "# Purpose\nProvides the Inseminations on a location\n",
        "tags": [
          "ADE-1-reproduction"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          },
          {
            "$ref": "#/components/parameters/start-date-time"
          },
          {
            "$ref": "#/components/parameters/end-date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the inseminations for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarReproInseminationEventCollection"
                },
                "examples": {
                  "finland": {
                    "$ref": "#/components/examples/insemination-finland"
                  }
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/drying-offs": {
      "get": {
        "operationId": "get-drying-offs",
        "summary": "Get the drying off for a certain location",
        "description": "# Purpose\nProvides the drying off on a location\n",
        "tags": [
          "ADE-1-reproduction"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          },
          {
            "$ref": "#/components/parameters/start-date-time"
          },
          {
            "$ref": "#/components/parameters/end-date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the drying off for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarMilkingDryOffEventCollection"
                },
                "examples": {
                  "finland": {
                    "$ref": "#/components/examples/drying-off-finland"
                  },
                  "sweden": {
                    "$ref": "#/components/examples/drying-off-sweden"
                  }
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/abortions": {
      "get": {
        "operationId": "get-abortions",
        "summary": "Get the abortion events for a certain location",
        "description": "# Purpose\nProvides the abortion events on a location\n",
        "tags": [
          "ADE-1-reproduction"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          },
          {
            "$ref": "#/components/parameters/start-date-time"
          },
          {
            "$ref": "#/components/parameters/end-date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the abortion events for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarReproAbortionEventCollection"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/parturitions": {
      "get": {
        "operationId": "get-parturitions",
        "summary": "Get the parturition events for a certain location",
        "description": "# Purpose\nProvides the Parturition events on a location\n",
        "tags": [
          "ADE-1-reproduction"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          },
          {
            "$ref": "#/components/parameters/start-date-time"
          },
          {
            "$ref": "#/components/parameters/end-date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the Parturition events for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarReproParturitionEventCollection"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/weights": {
      "get": {
        "operationId": "get-weights",
        "summary": "Get the weight data of animals",
        "description": "# Purpose\nProvides weight data from animals on a farm.",
        "tags": [
          "ADE-1-other"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          },
          {
            "$ref": "#/components/parameters/start-date-time"
          },
          {
            "$ref": "#/components/parameters/end-date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the weight results for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarWeightEventCollection"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/devices": {
      "get": {
        "operationId": "get-devices",
        "summary": "Get the device data for a location",
        "description": "# Purpose\nProvides device data for devices present on a farm.",
        "tags": [
          "ADE-1-other"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          },
          {
            "$ref": "#/components/parameters/start-date-time"
          },
          {
            "$ref": "#/components/parameters/end-date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the device data for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarDeviceCollection"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/locations/{location-scheme}/{location-id}/mating-recommendations": {
      "get": {
        "operationId": "get-mating-recommendations",
        "summary": "Get the mating recommendations for a certain location",
        "description": "# Purpose\nProvides the mating recommendations on a location\n",
        "tags": [
          "ADE-1-reproduction"
        ],
        "parameters": [{
            "$ref": "#/components/parameters/location-scheme"
          },
          {
            "$ref": "#/components/parameters/location-id"
          },
          {
            "$ref": "#/components/parameters/start-date-time"
          },
          {
            "$ref": "#/components/parameters/end-date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful. The response contains the mating recommendations for the given location",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/icarReproMatingRecommendationCollection"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "error": {
        "$ref": "../resources/exampleErrorResource.json"
      },
      "icarMilkingVisitEventCollection": {
        "$ref": "../collections/icarMilkingVisitEventCollection.json"
      },
      "icarReproMatingRecommendationCollection": {
        "$ref": "../collections/icarReproMatingRecommendationCollection.json"
      },
      "icarTestDayResultEventCollection": {
        "$ref": "../collections/icarTestDayResultEventCollection.json"
      },
      "icarLactationCollection": {
        "$ref": "../collections/icarLactationCollection.json"
      },
      "icarMovementBirthEventCollection": {
        "$ref": "../collections/icarMovementBirthEventCollection.json"
      },
      "icarMovementDeathEventCollection": {
        "$ref": "../collections/icarMovementDeathEventCollection.json"
      },
      "icarMovementArrivalEventCollection": {
        "$ref": "../collections/icarMovementArrivalEventCollection.json"
      },
      "icarMovementDepartureEventCollection": {
        "$ref": "../collections/icarMovementDepartureEventCollection.json"
      },
      "icarAnimalCoreCollection": {
        "$ref": "../collections/icarAnimalCoreCollection.json"
      },
      "icarReproPregnancyCheckEventCollection": {
        "$ref": "../collections/icarReproPregnancyCheckEventCollection.json"
      },
      "icarReproHeatEventCollection": {
        "$ref": "../collections/icarReproHeatEventCollection.json"
      },
      "icarReproInseminationEventCollection": {
        "$ref": "../collections/icarReproInseminationEventCollection.json"
      },
      "icarMilkingDryOffEventCollection": {
        "$ref": "../collections/icarMilkingDryOffEventCollection.json"
      },
      "icarReproAbortionEventCollection": {
        "$ref": "../collections/icarReproAbortionEventCollection.json"
      },
      "icarReproParturitionEventCollection": {
        "$ref": "../collections/icarReproParturitionEventCollection.json"
      },
      "icarWeightEventCollection": {
        "$ref": "../collections/icarWeightEventCollection.json"
      },
      "icarDeviceCollection": {
        "$ref": "../collections/icarDeviceCollection.json"
      }
    },
    "parameters": {
      "location-scheme": {
        "name": "location-scheme",
        "in": "path",
        "description": "The scheme id for the location identifier.",
        "required": true,
        "schema": {
          "type": "string",
          "enum": [
            "nl.ubn",
            "de.farmid",
            "be.pen"
          ]
        }
      },
      "location-id": {
        "name": "location-id",
        "in": "path",
        "description": "The unique identifier for the location.",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      "start-date-time": {
        "name": "start-date-time",
        "in": "query",
        "description": "The start of the date-time range for the data to get in the request.",
        "schema": {
          "type": "string",
          "format": "date-time"
        }
      },
      "end-date-time": {
        "name": "end-date-time",
        "in": "query",
        "description": "The end of the date-time range for the data to get in the request.",
        "schema": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "responses": {
      "default": {
        "description": "An error has occured while handling the request. Check the content of the message for the error details.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "errors": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/error"
                  }
                }
              },
              "description": "A default response containing only a list of errors"
            }
          }
        }
      }
    },
    "examples": {
      "arrival": {
        "value": {
          "view": {
            "totalItems": 1,
            "totalPages": 1,
            "pageSize": 10,
            "currentPage": 1
          },
          "member": [{
            "id": "ac9bdd26-0e20-44e7-b311-7d3d988f9717",
            "animal": {
              "id": "NL 919713288",
              "scheme": "nl.ubn"
            },
            "eventDateTime": "2016-01-06",
            "location": {
              "id": "231817",
              "scheme": "nl.ubn"
            },
            "animalDetail": {
              "alternativeIdentifiers": [],
              "species": "Cattle",
              "gender": "Female",
              "birthDate": "2013-11-06",
              "breedFractions": {
                "denominator": "8",
                "fractions": [{
                  "breed": {
                    "id": "HF",
                    "scheme": "icar.org"
                  },
                  "fraction": "8"
                }]
              },
              "coatColor": "RB",
              "managementTag": "88",
              "name": "NELLY 258",
              "productionPurpose": "Milk",
              "status": "Alive",
              "parentage": [{
                  "parentOf": {
                    "id": "NL 919713288",
                    "scheme": "nl.ubn"
                  },
                  "gender": "Female",
                  "relation": "Genetic",
                  "identifier": {
                    "id": "NL 765410142",
                    "scheme": "nl.ubn"
                  },
                  "officialName": "NELLY 211"
                },
                {
                  "parentOf": {
                    "id": "NL 919713288",
                    "scheme": "nl.ubn"
                  },
                  "gender": "Male",
                  "relation": "Genetic",
                  "identifier": {
                    "id": "NL 399745212",
                    "scheme": "nl.ubn"
                  },
                  "officialName": "TOPSPEED KODAK"
                }
              ]
            }
          }]
        }
      },
      "milking-visit": {
        "value": {
          "view": {
            "totalItems": 1,
            "totalPages": 1,
            "pageSize": 10,
            "currentPage": 1
          },
          "member": [{
            "id": "706250",
            "animal": {
              "id": "NL 877034232",
              "scheme": "nl-v1"
            },
            "milkingStartingDateTime": "2019-11-01T23:58:31",
            "milkingVisitDuration": {
              "value": 349.0,
              "unitCode": "SEC"
            },
            "milkingDuration": {
              "value": "210",
              "unitCode": "SEC"
            },
            "milkingType": "Automated",
            "milkingMilkWeight": {
              "value": 3.5,
              "unitCode": "KGM"
            },
            "milkingComplete": true,
            "milkingParlourUnit": "101",
            "milkingBoxNumber": 0,
            "milkingDeviceId": "101",
            "measureDeviceId": "101",
            "eventOffset": "2019-11-01T23:58:31",
            "eventDeviceId": "101",
            "quarterMilkings": [{
              "icarQuarterId": "LF",
              "milkingDuration": {
                "value": "210",
                "unitCode": "SEC"
              },
              "milkingMilkWeight": {
                "value": 3.5,
                "unitCode": "KGM"
              }
            }],
            "animalMilkingSample": [{
              "bottleIdentifierType": "BRC",
              "rackNumber": "3",
              "bottlePosition": "7"
            }],
            "icarMilkCharacteristics": [{
                "characteristic": "FAT",
                "value": "3.74",
                "unit": "VP",
                "icarMeasuringDevice": "to_be_defined_by_ICAR-sensor_group"
              },
              {
                "characteristic": "PROTEIN",
                "value": "3.54",
                "unit": "VP"
              }
            ]
          }]
        }
      },
      "test-day-result": {
        "value": {
          "view": {
            "totalItems": 1,
            "totalPages": 1,
            "pageSize": 10,
            "currentPage": 1
          },
          "member": [{
            "id": "706250",
            "animal": {
              "id": "NL 877034232",
              "scheme": "nl-v1"
            },
            "EventDateTime": "2019-11-01T23:58:31",
            "milkWeight24Hours": {
              "value": "21.7",
              "unitCode": "KGM"
            },
            "testDayCode": "0",
            "icarMilkCharacteristics": [{
                "characteristic": "FAT",
                "value": "3.74",
                "unit": "VP",
                "icarMeasuringDevice": "to_be_defined_by_ICAR-sensor_group"
              },
              {
                "characteristic": "PROTEIN",
                "value": "3.54",
                "unit": "VP"
              }
            ]
          }]
        }
      },
      "insemination-finland": {
        "value": {
          "summary": "Example of insemination event messages from finnish milk recording organization",
          "externalValue": "../examples/exampleInseminationEventResources_Finland.json"
        }
      },
      "pregnancy-check-finland": {
        "value": {
          "summary": "Example of pregnancy check event messages from finnish milk recording organization",
          "externalValue": "../examples/examplePregnancyCheckEventResources_Finland.json"
        }
      },
      "drying-off-finland": {
        "value": {
          "summary": "Example of drying off event messages from finnish milk recording organization",
          "externalValue": "../examples/exampleDryOffEventResources_Finland.json"
        }
      },
      "drying-off-sweden": {
        "value": {
          "summary": "Example of drying off event messages from swedish milk recording organization",
          "externalValue": "../examples/exampleDryOffEventResources_Sweden.json"
        }
      }
    }
  }
}
